# Generated by Django 2.2.12 on 2020-06-21 01:44

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '__first__'),
        ('trust', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_decision_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_decision_re_sender', otree.db.models.IntegerField(null=True)),
                ('sender_belief_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_belief_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_correct_guess', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('sender_belief_diff', otree.db.models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MegaSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('payoff_calculated', models.BooleanField(default=False)),
                ('groups_formed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PseudoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_decision_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_decision_re_sender', otree.db.models.IntegerField(null=True)),
                ('sender_belief_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_belief_re_receiver', otree.db.models.IntegerField(null=True)),
                ('receiver_correct_guess', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('sender_belief_diff', otree.db.models.IntegerField(null=True)),
                ('megasession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudogroups', to='mingle.MegaSession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MingleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust.City')),
                ('megasession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minglesessions', to='mingle.MegaSession')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minglesession', to='otree.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MegaParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust.City')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megaparticipants', to='mingle.MegaGroup')),
                ('megasession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='megaparticipants', to='mingle.MegaSession')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otree.Participant')),
                ('pseudogroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megaparticipants', to='mingle.PseudoGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='megagroup',
            name='megasession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='megagroups', to='mingle.MegaSession'),
        ),
    ]
