# Generated by Django 2.2.12 on 2020-07-13 23:19

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('mingle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megagroup',
            name='receiver_belief_re_receiver',
        ),
        migrations.RemoveField(
            model_name='pseudogroup',
            name='receiver_belief_re_receiver',
        ),
        migrations.AddField(
            model_name='megagroup',
            name='has_sender_sent',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='megagroup',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='mingle.MegaParticipant'),
        ),
        migrations.AddField(
            model_name='megagroup',
            name='receiver_belief_re_sender',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='megagroup',
            name='sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_group', to='mingle.MegaParticipant'),
        ),
        migrations.AddField(
            model_name='megagroup',
            name='sender_guess_payoff',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='megaparticipant',
            name='payoff_calculated',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='pseudogroup',
            name='has_sender_sent',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='pseudogroup',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_pseudogroup', to='mingle.MegaParticipant'),
        ),
        migrations.AddField(
            model_name='pseudogroup',
            name='receiver_belief_re_sender',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pseudogroup',
            name='sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_pseudogroup', to='mingle.MegaParticipant'),
        ),
        migrations.AddField(
            model_name='pseudogroup',
            name='sender_guess_payoff',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megagroup',
            name='receiver_correct_guess',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='megagroup',
            name='receiver_decision_re_sender',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megagroup',
            name='sender_belief_diff',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megagroup',
            name='sender_belief_re_receiver',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='megagroup',
            name='sender_decision_re_receiver',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pseudogroup',
            name='receiver_correct_guess',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='pseudogroup',
            name='receiver_decision_re_sender',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pseudogroup',
            name='sender_belief_diff',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pseudogroup',
            name='sender_belief_re_receiver',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pseudogroup',
            name='sender_decision_re_receiver',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
    ]
